Release version 5.0.0-rc.2

diff --git a/bin/coverage b/bin/coverage
--- a/bin/coverage
+++ b/bin/coverage
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 # Generates code coverage statistics and opens it in your browser
 
-mix coveralls || { echo 'Tests failed!'; exit 1; }
+mix coveralls.html || {
+    echo 'Tests failed!'
+    exit 1
+}
 open cover/excoveralls.html
