Install coveralls

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -3,7 +3,12 @@
 MIX_ENV=test mix compile --warnings-as-errors --force || { echo 'Please fix all compiler warnings.'; exit 1; }
 MIX_ENV=test mix credo --strict --ignore design,consistency || { echo 'Elixir code failed Credo linting. See warnings above.'; exit 1; }
 MIX_ENV=test mix docs || { echo 'Elixir HTML docs were not generated!'; exit 1; }
-mix test || { echo 'Elixir tests on Torch failed!'; exit 1; }
+
+if [ $CI ]; then
+  mix coveralls || { echo 'Elixir tests on Torch failed!'; exit 1; }
+else
+  mix test || { echo 'Elixir tests on Torch failed!'; exit 1; }
+fi
 
 # Run integration tests
 cd test/support/apps/example && {
