[tests] Add specific tests for phx 1.3 and 1.4

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -20,6 +20,6 @@ if [ $CI ]; then
 fi
 
 # Run integration tests
-cd test/support/apps/example && {
-  bin/test || { echo 'Integration tests on regular Phoenix project failed!'; exit 1; }
+cd test/support/apps/phx1_3 && {
+  bin/test || { echo 'Integration tests on regular Phoenix 1.3 project failed!'; exit 1; }
 }
