Added tests and support for Phoenix 1.5

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -5,6 +5,8 @@ MIX_ENV=test mix credo --strict --ignore design,consistency || { echo 'Elixir co
 MIX_ENV=test mix docs || { echo 'Elixir HTML docs were not generated!'; exit 1; }
 MIX_ENV=test mix test || { echo 'Elixir tests on Torch failed!'; exit 1; }
 
+TEST_ROOT="$(pwd)/test"
+
 if [ $CI ]; then
   if [ $TRAVIS ]; then
     echo "----------------------------------------------------------"
@@ -20,6 +22,14 @@ if [ $CI ]; then
 fi
 
 # Run integration tests
-cd test/support/apps/phx1_3 && {
+cd "$TEST_ROOT/support/apps/phx1_3" && {
   bin/test || { echo 'Integration tests on regular Phoenix 1.3 project failed!'; exit 1; }
+}
+
+cd "$TEST_ROOT/support/apps/phx1_4" && {
+  bin/test || { echo 'Integration tests on regular Phoenix 1.4 project failed!'; exit 1; }
+}
+
+cd "$TEST_ROOT/support/apps/phx1_5" && {
+  bin/test || { echo 'Integration tests on regular Phoenix 1.5 project failed!'; exit 1; }
 }
