[tests] Cleanup artifacts even during test failure
Idea taken from PR #169 commit 8207e954 by scorsi

diff --git a/test/support/apps/phx1_5/bin/test b/test/support/apps/phx1_5/bin/test
--- a/test/support/apps/phx1_5/bin/test
+++ b/test/support/apps/phx1_5/bin/test
@@ -1,24 +1,27 @@
 #!/usr/bin/env bash
 
+# Clean up generated files
+function cleanup() {
+    rm -rf priv/templates
+    rm -rf priv/repo/migrations/*.exs
+    rm -rf lib/phx1_5/blog.ex
+    rm -rf lib/phx1_5/blog
+    rm -rf test/phx1_5/blog_test.exs
+    rm -rf lib/phx1_5_web/controllers/post_controller.ex
+    rm -rf lib/phx1_5_web/templates/layout/torch.html.eex
+    rm -rf lib/phx1_5_web/templates/post/
+    rm -rf lib/phx1_5_web/views/post_view.ex
+    rm -rf test/phx1_5_web/controllers/post_controller_test.exs
+    cp ../../routers/phx1_5_original.ex lib/phx1_5_web/router.ex
+}
+
 mix deps.get || { echo 'Dependencies could not be fetched!'; exit 1; }
 MIX_ENV=test mix ecto.drop || { echo 'Database could not be dropped'; exit 1; }
 MIX_ENV=test mix torch.install || { echo 'Torch could not be installed!'; exit 1; }
 MIX_ENV=test mix torch.gen.html Blog Post posts title:string published:boolean published_at:datetime views:integer || { echo 'Torch files not generated!'; exit 1; }
 cp ../../routers/phx1_5_modified.ex lib/phx1_5_web/router.ex
-mix test || { echo 'Tests failed!'; exit 1; }
-
-# Clean up generated files
-rm -rf priv/templates
-rm -rf priv/repo/migrations/*.exs
-rm -rf lib/phx1_5/blog.ex
-rm -rf lib/phx1_5/blog
-rm -rf test/phx1_5/blog_test.exs
-rm -rf lib/phx1_5_web/controllers/post_controller.ex
-rm -rf lib/phx1_5_web/templates/layout/torch.html.eex
-rm -rf lib/phx1_5_web/templates/post/
-rm -rf lib/phx1_5_web/views/post_view.ex
-rm -rf test/phx1_5_web/controllers/post_controller_test.exs
-cp ../../routers/phx1_5_original.ex lib/phx1_5_web/router.ex
+mix test || { echo 'Tests failed!'; cleanup; exit 1; }
+cleanup
 
 echo 'Tests succeeded!'
 exit 0
